title: "情報系のための Dev Container による LaTeX 環境構築"
summary: "この Zenn Book では Dev Container を使って LaTeX 環境を構築する手順を解説します．Windows に LaTeX を直接インストールすると非常に長い時間を要するのに対して，Dev Container を使うとインストールにかかる時間を大幅に短縮できます．また，VS Code の LaTeX Workshop 拡張機能を使うことで，Cloud LaTeX や Overleaf と同じようにプレビューを見ながらソーステキストを編集する体験も実現できます．個人が作成した Docker イメージではなく TeX Live 公式の Docker イメージを使用するため，メンテナンス性や信頼性の面でも優れています．Docker をベースにしているため，GitHub Actions を用いた自動ビルドパイプラインの構築とも相性が良いです．Docker や Dev Container を使ったことがない人に向けて丁寧に解説しているので，初心者の人も安心して読み進めることができます．"
topics: [ "latex", "devcontainer", "docker", "vscode", "windows" ]
published: true
price: 0 # 有料の場合200〜5000
chapters:
  - "01cc83496d0318.md"
  - "0346c03611c598.md"
  - "3e79df7c2a5fd0.md"
  - "4dcea76ca9bdd8.md"
  - "59f917895fb0f8.md"
  - "74e55ea30f561d.md"
  - "684b5eb5d97bc8.md"
  - "9308fc321d7df0.md"
  - "a0084e077cc8b8.md"
  - "fea78ace18f64d.md"
  - "a5644f54259798.md"
  - "cb0a395dfeb518.md"
  - "daf886439eb028.md"
  - "35cf565a063130.md"
